### ISSUE TITLE
可不可以提供修改推流Metadata信息的方法？

### ISSUE THREAD

**Issue by toss156** [ksvc/KSYLive_iOS#100]
可不可以提供修改推流Metadata信息的方法，我们需要在metadata加入自定义的信息，用来标示流信息。

**Comment by pengbins** [comment]
已经提供了的, API文档里可以查到的
[KSYStreamerBase.streamMetaData](http://ksvc.github.io/KSYLive_iOS/doc/html/Classes/KSYStreamerBase.html#//api/name/streamMetaData)

**Comment by toss156** [comment]
测试了下，自定义的可以添加，但是覆盖不了原来的字段 
![image](https://user-images.githubusercontent.com/3478955/29017721-ac998892-7b8a-11e7-82fc-b203937d4168.png)
用ffplay看流里面的metadata encoder还是原来的
![image](https://user-images.githubusercontent.com/3478955/29017744-c1668d74-7b8a-11e7-9ace-ca7f9c8be8c3.png)

**Comment by fpzeng** [comment]
encoder不是推流SDK添加的，是你使用的直播CDN添加的。
请联系CDN更改配置。

**Comment by toss156** [comment]
应该不是CDN添加的，我用其他的推流SDK可以修改成功的。

**Comment by toss156** [comment]
查了下，可能是ffmpeg 里面 [libavformat/mux.c](https://github.com/FFmpeg/FFmpeg/blob/f483949188dcb2f4c546603bd478100190ee5312/libavformat/mux.c) 中修改的encoder。请问 SDK中是否使用了推流过程中是否使用了libavformat? 是否可以修改使其不要覆盖自定义的设置?  @pengbins @fpzeng 

```
 /* set muxer identification string */
    if (!(s->flags & AVFMT_FLAG_BITEXACT)) {
        av_dict_set(&s->metadata, "encoder", LIBAVFORMAT_IDENT, 0);
    } else {
        av_dict_set(&s->metadata, "encoder", NULL, 0);
    }

    for (e = NULL; e = av_dict_get(s->metadata, "encoder-", e, AV_DICT_IGNORE_SUFFIX); ) {
        av_dict_set(&s->metadata, e->key, NULL, 0);
    }
```

**Comment by pengbins** [comment]
这个不太合适呀, 你们添加自定义的字段的话, 换个自定义的key会不会更好呢?

**Comment by toss156** [comment]
嗯。只能这样了。
