### ISSUE TITLE
偶发性的，开启推流屏幕一直是黑的，但是拉流端能看到画面，请问这是什么原因 

### ISSUE THREAD

**Issue by BlackCatSun** [ksvc/KSYLive_iOS#101]

**Comment by pengbins** [comment]
请问预览是用的 GPUImageView 还是KSYGPUView呢? 建议使用[KSYGPUView](http://ksvc.github.io/KSYLive_iOS/doc/html/Classes/KSYGPUView.html).

预览黑屏可能是在View的frame size设置为正确的值之前, 就开始了刷数据. 可以适当调整一下这个时序, 应该可以避免这个问题.

**Comment by BlackCatSun** [comment]
请问您说的预览指的是什么，是你们demo里在view will apear 里设置的吗
<img width="734" alt="2017-08-23 10 59 15" src="https://user-images.githubusercontent.com/25749083/29597227-d0d58998-87f3-11e7-995a-f2aaced7dd65.png">

**Comment by pengbins** [comment]
预览就是主播在他自己手机上看到的摄像头的画面....

你们用的是哪个版本的SDK呢?  可以尝试更新到v2.6.0, 应该没有类似的问题了

**Comment by BlackCatSun** [comment]
2.1.0,只要更新下版本就可以了是吗
请问用你们的画中画推流这样是初始化有问题吗，在10.3.3出现闪退
<img width="604" alt="2017-08-22 17 02 05" src="https://user-images.githubusercontent.com/25749083/29602908-a010cdba-8814-11e7-843d-ac70243a5fa0.png">

**Comment by jiangdsuccess** [comment]
你可以升级版本以后，调试一下看看，贴一下具体信息
