### ISSUE TITLE
旁路录制好像有问题

### ISSUE THREAD

**Issue by 577528249** [ksvc/KSYLive_iOS#103]
开直播的时候，边推流边旁路录制，分享直播到微信后，再回来就录制就停止了，然后我们就监听app进入后台和进入前台的通知，并在之后进行录制，但是录制的视频会把之前的视频覆盖掉，分享之前的直播的视频就看不到了，
@objc private func tempLeaveLive() {//接受到app进入后台的通知后的方法
        print("=========tempLeaveLive")
        kit?.appEnterBackground()
        sendStreamStatusToServer(.tempLeave)
    }
    
    @objc private func comeBackLive() {//接受到app进入前台的通知后的方法
        print("============ comeBackLive")
        kit?.appBecomeActive()
        let path = NSSearchPathForDirectoriesInDomains(FileManager.SearchPathDirectory.documentDirectory, FileManager.SearchPathDomainMask.userDomainMask, true).last!
        let url: URL = URL.init(fileURLWithPath: "\(path)/\(self.streamName).mp4")
        self.kit?.streamerBase.startBypassRecord(url)
        sendStreamStatusToServer(.isStreaming)
    }

**Comment by pengbins** [comment]
建议每次录制成不同的文件, 最后用其他方法将这些片段拼接在一起

**Comment by pengbins** [comment]
比如使用 系统API来做连接, 参考: https://stackoverflow.com/questions/38972829/swift-merge-avasset-videos-array
