### ISSUE TITLE
推流怎么设置自定义的SIZE呢？ how to decide the size of push video.

### ISSUE THREAD

**Issue by leewaycn** [ksvc/KSYLive_iOS#104]
as above.

**Comment by pengbins** [comment]
size 是指分辨率么?
编码推流的分辨率(size) 可以用  [streamDimension](http://ksvc.github.io/KSYLive_iOS/doc/html/Classes/KSYGPUStreamerKit.html#//api/name/streamDimension)

详细的解析可以参考[wiki](https://github.com/ksvc/KSYLive_iOS/wiki/customOutputSize)
