### ISSUE TITLE
请问推流 的分辨率怎么设置  默认是多少 

### ISSUE THREAD

**Issue by BlackCatSun** [ksvc/KSYLive_iOS#106]

**Comment by pengbins** [comment]
与 #104 重复了



_kit.streamDimension 默认值为(640, 360)

编码推流的分辨率 请参考 [API文档][1] ,  [wiki][2]
```
/**
 @abstract   用户定义的视频 **推流** 分辨率
 @discussion 有效范围: 宽度[160, 1280] 高度[ 90,  720], 超出范围会取边界有效值
 @discussion 其他与previewDimension限定一致,
 @discussion 当与previewDimension不一致时, 同样先裁剪到相同宽高比, 再进行缩放
 @discussion 默认值为(640, 360)
 @see previewDimension
 */
@property (nonatomic, assign)   CGSize streamDimension;
```

PS: 😢  您完全不会举一反三么? 😢 
 
[1]:http://ksvc.github.io/KSYLive_iOS/doc/html/Classes/KSYGPUStreamerKit.html#//api/name/streamDimension
[2]:https://github.com/ksvc/KSYLive_iOS/wiki/customOutputSize
