### ISSUE TITLE
用你们的推流工具错线闪退在友盟统计上出现的，请问能看出来什么原因吗

### ISSUE THREAD

**Issue by BlackCatSun** [ksvc/KSYLive_iOS#108]
<img width="922" alt="2017-08-22 16 27 30" src="https://user-images.githubusercontent.com/25749083/29556004-0b2efbbc-8757-11e7-81ff-a4c6e3898d68.png">

**Comment by pengbins** [comment]
这个一般是在后台调用了GPU渲染出现的问题, 请问你们有修改 kit 中前后台切换相关的代码吗?

**Comment by BlackCatSun** [comment]
1.什么是前后台切换代码？我只在app上用到你们的代码   用的是画中画，调用是顺序是
<img width="604" alt="2017-08-22 17 02 05" src="https://user-images.githubusercontent.com/25749083/29557551-0c067420-875c-11e7-911f-180f8794400d.png">

<img width="283" alt="2017-08-22 17 02 32" src="https://user-images.githubusercontent.com/25749083/29557567-1737dadc-875c-11e7-9dc4-1f4a91c335ed.png">

2.请问Gpu渲染是什么

**Comment by jiangdsuccess** [comment]
调用顺序没问题，我这边没有复现你这边的问题，请更新版本，参考demo进行集成
