### ISSUE TITLE
跟VR SDK有冲突，音频卡顿

### ISSUE THREAD

**Issue by liuminzhong** [ksvc/KSYLive_iOS#109]
项目里集成了VR SDK，推流后播放出来的音频像拖拉机一样卡顿，视频正常。求助。 版本是2.6.1最新。动态库方式引入。如果同时混入一路背景音乐，推流后播放出来背景音乐不卡，只是麦克风采集的音频卡顿。

**Comment by liuminzhong** [comment]
使用KSYAudioCap_AVCaptureDevice，声音不卡了。  但后台无法录制音频了。KSYAudioCap_AudioUnit有方法解决音频卡顿问题吗？

**Comment by pengbins** [comment]
VR SDK 是指哪个呢?

**Comment by liuminzhong** [comment]
谢谢，解决了。再问个下，第一个直播设置页面startPreview - stopPreview - 设置kit=nil，然后跳直播页面 setupKit - startPreview，主线程卡死了，有什么解决方法吗？

**Comment by pengbins** [comment]
可以监听一下  kit的 消息通知 , stopPreview 真正完成会有通知的

**Comment by liuminzhong** [comment]
直播设置页面 跳转到直播页面前调用了
    [_kit stopPreview];
    _kit = nil;
然后在直播页面初始化kit时，主线程卡死在_kit = [[KSYGPUStreamerKit alloc] initWithDefaultCfg]; 这句。
