### ISSUE TITLE
如何降低推流回音

### ISSUE THREAD

**Issue by nan1001** [ksvc/KSYLive_iOS#111]
同時拉流和推流時，視頻的回音很大，請問如何解決?

**Comment by pengbins** [comment]
请问什么是 同时拉流和推流?

**Comment by nan1001** [comment]
视频通话场景下，摄像头采集，拉远程流播放，当前效果回声颇为严重，很希望SDK能有采集端回声抑制功能。

**Comment by pengbins** [comment]
连麦场景的话建议参考 https://github.com/ksvc/KSYDiversityLive_iOS/tree/master/agoraRtc

直播SDK的音频采集提供了回声抑制的接口 [enableVoiceProcess](http://ksvc.github.io/KSYLive_iOS/doc/html/Classes/KSYAUAudioCapture.html#//api/name/enableVoiceProcess), 可以尝试用一下, 不过开启此开关后, 变声,混响等功能不能生效了.
