### ISSUE TITLE
Use KSYBeautifyProFilter crash

### ISSUE THREAD

**Issue by duckscorpion13** [ksvc/KSYLive_iOS#112]
self.pushKit?.setupFilter(KSYBeautifyProFilter()) <-Crash

libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by pengbins** [comment]
崩溃应该是有图片资源没找到,  请参考wiki 将必须的png图片放到bundle中
https://github.com/ksvc/KSYLive_iOS/wiki/filter

**Comment by duckscorpion13** [comment]
我加入了KSYGPUResource.bundle還是一樣會crash

**Comment by pengbins** [comment]
我们demo中也用到了这个滤镜的, 并没有crash哦, 检查下看bundle是不是没加对吧

**Comment by duckscorpion13** [comment]
bundle需要針對我的專案做什麼額外設定嗎？

**Comment by pengbins** [comment]
并不需要, 对比我们demo里的添加方式看看,有什么区别呢

**Comment by duckscorpion13** [comment]
我直接把你demo的bundle檔拖曳到我的專案添加的
是不是這種方式不對？

**Comment by pengbins** [comment]
滤镜内读取文件的方式, 可以检查下是否能读取到图片
```
    NSString * path = [[NSBundle mainBundle] pathForResource:@"KSYGPUResource" ofType:@"bundle"];
    path = [path stringByAppendingPathComponent:@"0_pink.png"];
```

**Comment by duckscorpion13** [comment]
感謝你   我創造一個新的同名bundle檔案後就能抓到了
