### ISSUE TITLE
自定义推流问题

### ISSUE THREAD

**Issue by borisyue** [ksvc/KSYLive_iOS#114]
客户端：iOS11
我在开发的时候发现开启推流[kit.streamerBase startStream:url]不能连接到rtmp服务器，必须开启[kit startPreview:View]后才连接到服务器开始推流。
我这里有一个需求是自定义推流，不使用摄像头startPreview来采集数据推流。
我如何在不需要startPreview的情况下使用[kit.streamerBase processVideoSampleBuffer:(CMSampleBufferRef)sampleBuffer]来推自定义的数据流。

**Comment by pengbins** [comment]
默认情况下 streamerBase 需要同时接收到音频数据和视频数据之后才能开始推流

如果你们只调用了 processVideoSampleBuffer, 送入视频数据, streamerBase会一直等待音频数据

建议的解决方案:
方案一:  如果你们有音频数据, 通过 processAudioSampleBuffer 送入音频数据
方案二:  如果你们不需要音频, 通过streamerBase.bWithAudio = NO , 来关闭音频通路, 纯视频推流

请根据具体情况选择.

**Comment by pengbins** [comment]
相关说明 补充到[wiki][1]中了

[1]:https://github.com/ksvc/KSYLive_iOS/wiki/streamStat#%E5%90%AF%E5%8A%A8%E6%8E%A8%E6%B5%81%E5%90%8E%E5%8D%A1%E4%BD%8F
