### ISSUE TITLE
推流崩溃 ios 11.0.2

### ISSUE THREAD

**Issue by alexluan** [ksvc/KSYLive_iOS#115]
ios 11.0.2
 [selfWeak.streamerBase processVideoPixelBuffer:pixelBuffer
                                         timeInfo:timeInfo];
 推流崩溃 提示：Enqueued from com.sunsetlakesoftware.GPUImage.openGLESContextQueue (Thread 82)

**Comment by pengbins** [comment]
请提供完整的堆栈信息, 和复现步骤

**Comment by alexluan** [comment]
![2017-10-19 18 43 29](https://user-images.githubusercontent.com/11609551/31868917-ac72b176-b7d6-11e7-9e6a-852e83347161.png)
![2017-10-19 18 43 37](https://user-images.githubusercontent.com/11609551/31868918-ac9c3a1e-b7d6-11e7-9b14-f9102fd2a20f.png)

ios 11.0.2 ，先预览(没有问题)，开始推流，崩溃 其他 ios 版本没有问题

**Comment by pengbins** [comment]
请问下, 在我们demo上能复现么? 如果可以的话, 能否提供一下步骤

**Comment by pengbins** [comment]
请问你们项目里有其他部分用了FFmpeg不?

**Comment by alexluan** [comment]
demo 没有问题的，
pod 'Bugly'
# YYImage 仅demo中用于导入gif和apng的格式的图片用到了
# 不需要支持这些格式的话,不需要添加YYImage的依赖
pod 'YYImage'

#播放器-金山
pod 'GPUImage'

#pod 'libksygpulive'
pod 'libksygpulive/KSYGPUResource'
pod 'libksygpulive/libksygpulive', '~> 2.8.0'

有问题

**Comment by alexluan** [comment]
一行代码没有修改，把 pod 'libksygpulive/libksygpulive', '~> 2.8.0' 修改成 pod 'libksygpulive/libksygpulive' 重新 pod update 就不会有崩溃问题了

**Comment by pengbins** [comment]
```
pod 'libksygpulive/libksygpulive' 
```

能看下 使用这句的时候的 Podfile.lock 文件的内容吗?

看看实际安装的是什么版本的

**Comment by alexluan** [comment]
- libksygpulive/base (2.8.0)
  - libksygpulive/KSYGPUResource (2.8.0)
  - libksygpulive/libksygpulive (2.8.0):
    - GPUImage
    - libksygpulive/streamerbase
  - libksygpulive/mediacodec (2.8.0)
  - libksygpulive/mediacore_enc_base (2.8.0)
  - libksygpulive/mediacore_enc_lite (2.8.0)
  - libksygpulive/streamerbase (2.8.0):
    - libksygpulive/base
    - libksygpulive/mediacodec
    - libksygpulive/mediacore_enc_base
    - libksygpulive/mediacore_enc_lite
    - libksygpulive/yuv

**Comment by pengbins** [comment]
额, 那还是2.8.0 呀, 用的库是同一个...

```
 pod 'libksygpulive/libksygpulive', '~> 2.8.0'
```

**Comment by alexluan** [comment]
对的，我也不知道原因，上周还不行。可能这边pod 仓库的问题吧

**Comment by alexluan** [comment]
能加你的 qq 或者微信吗，现在崩溃问题有出来了

**Comment by pengbins** [comment]
QQ讨论群：574179720 [视频云技术交流群]

**Comment by alexluan** [comment]
好吧，找到问题了，我这边 推流地址有问题（http: ）,应该是（rtmp：），但是，是不是也不应该崩溃啊

**Comment by pengbins** [comment]
http 地址无法进行推流, SDK应该提前报错, 我们再定位一下看吧, 谢谢反馈

**Comment by pengbins** [comment]
问题修复上线了  https://github.com/ksvc/KSYLive_iOS/releases/tag/v2.9.1
