### ISSUE TITLE
推流，logo 水印

### ISSUE THREAD

**Issue by alexluan** [ksvc/KSYLive_iOS#117]
需求：1、希望水印logo 靠右边对齐便宜一定的距离。2、希望水印logo，向下便宜一定的距离
问题描述：x y 的总是设置不对。在，官方demo 中也会有相同的问题，

**Comment by pengbins** [comment]
主要有哪些尺寸是变化的呢? 
如果 水印的尺寸比较固定的话 可以试试:
```
 x =  (1-logo.width/preview.width - offset.x)
// y 同理
```

**Comment by alexluan** [comment]
你们的 demo 中这样修改 logo 的位置也是不正确的，位置问题还是没解决
_kit.logoRect = CGRectMake((1-logoImg.size.width/self.view.frame.size.width), yPos, 0, hgt);
或者
_kit.logoRect = CGRectMake((1-logoImg.size.width/self.view.frame.size.width - 35), yPos, 0, hgt);

**Comment by pengbins** [comment]
self.view.frame.size.width 这个得换成 预览的分辨率_kit.previewDimension.width

```
1-logoImg.size.width/self.view.frame.size.width - 35
```

35得换成  35/_kit.previewDimension.width
