### ISSUE TITLE
同时开启直播推流和科大讯飞语音识别，推的流会没有声音

### ISSUE THREAD

**Issue by luoxiao** [ksvc/KSYLive_iOS#121]
同时开启直播推流和科大讯飞语音识别，推的流会没有声音。
如题，怎么解决？

**Comment by pengbins** [comment]
可能是直播SDK的采集模块被科大讯飞语音识别打断了吧,  

你们是用的科大讯飞的语音识别SDK么? 如果是SDK的话, 可以看看他们的接口是否有送出数据的方法.
或者看看有没有关闭他们的采集, 改为将直播采集的数据送给他们.
