### ISSUE TITLE
RTMP seekTo faced MPMovieFinishReasonPlaybackError

### ISSUE THREAD

**Issue by AppsterDeveloper** [ksvc/KSYLive_iOS#124]
MoviePlayer KSYMoviePlayerController playing RTMP successfully. After dragging slider with seekto, player returned error MPMovieFinishReasonPlaybackError and video is stucked for few seconds. 

KSY Version: 2.9.2

**Comment by fpzeng** [comment]
Current SDK Version only supports live streaming play with RTMP protocol. Set url with HLS protocol for seekto operation.
