### ISSUE TITLE
能否单独设置前后摄像头对应的采集分辨率?

### ISSUE THREAD

**Issue by mgv5** [ksvc/KSYLive_iOS#125]
有些设备的前后摄像头支持的分辨率不一样, 后置的比前置的高, 如果 采集分辨率过高,前置的摄像头不支持,就无法切换前置摄像头.

**Comment by fpzeng** [comment]
能否举个具体的例子？
什么样的手机，配置的具体分辨率

**Comment by mgv5** [comment]
iPhone 4S,  streamerProfile 中采集分辨率为 1280 * 720 以及 960 * 540的都不能切换.  如 KSYStreamerProfile_540p_auto  ,  KSYStreamerProfile_720p_auto.

**Comment by mgv5** [comment]
另外 KSYStreamerProfile这个枚举对应的注释好像有问题,不对应.
KSYStreamerProfile_360p_1 , KSYStreamerProfile_360p_2, KSYStreamerProfile_360p_3,这三个的注释不对应

**Comment by pengbins** [comment]
@mgv5  前后摄像头分辨率分离 建议还是你们自己实现以下, 我们API理分辨率已经很多了, 容易弄混乱

你们在切换摄像头的时候在调用以下采集分辨率设置接口就好了

**Comment by pengbins** [comment]
KSYStreamerProfile 枚举的注释都是正确的哈,  360p说的都是推流的分辨率
