### ISSUE TITLE
KSYAUAudioCapture 录音回调转AAC播放问题

### ISSUE THREAD

**Issue by susazz** [ksvc/KSYLive_iOS#128]
SDK: ksylive
问题描述： 使用KSYAUAudioCapture回调参数CMSampleBufferRef转AAC保存本地播放。测试机6p,iOS9,声音正常。7p，iOS11，声音过快。
当使用7p的时候，1，录音 - 停止录音 - 录音 这种时候音频转码播放是正常的。
                               2，录音- 播放 -录音  这种时候音频转码播放不正常。
简单来说就是录音后播放在录音播放的时候就不正常了。
不正常的时候输出KSYAUAudioCapture回调参数CMSampleBufferRef 里面的numSamples为941，正常的时候为1024

**Comment by pengbins** [comment]
这个长度我们也无法控制哦, 建议方案有三个
1. 直接使用KSYStreamerBase, 关闭视频,进行[纯音频的编码][1], 输出为本地的音频文件
2. KSYAUAudioCapture回调后先送到 [KSYAudioMixer][2], 再把KSYAudioMixer的输出拿来进行AAC编码
3. KSYAUAudioCapture回调的数据先送到fifo中, 你们自行保证每次从fifo中取的数据长度都是1024

[1]:https://github.com/ksvc/KSYLive_iOS/wiki/pureAudioStream
[2]:http://ksvc.github.io/KSYLive_iOS/doc/html/Classes/KSYAudioMixer.html
