### ISSUE TITLE
画中画直播,如何设置 摄像头layer 和 bgPicLayer 的层级关系?

### ISSUE THREAD

**Issue by czeludzki** [ksvc/KSYLive_iOS#129]
如题,就如 bgPicLayer 显示在 摄像头Layer 之上, 十分感谢!
是会跟 mixer 的 masterLayer 有关系吗?
我想将 bgPicLayer 显示在 摄像头Layer 之上,并用了如下方式设置
`
[self.streamerKit.vStreamMixer setMasterLayer:self.streamerKit.bgPicLayer];
[self.streamerKit.vPreviewMixer setMasterLayer:self.streamerKit.bgPicLayer];
`
但是并没有效果

**Comment by pengbins** [comment]
http://ksvc.github.io/KSYLive_iOS/doc/html/Classes/KSYGPUPicMixer.html
>>  叠加顺序为0在最下层, index 越大在更上层

如果需要调整图层叠加顺序, 可以考虑修改KSYGPUPipStreamerKit.m的init函数中 bgPicLayer的初始数值, 改为 比较大的数值 , 比如6.
