### ISSUE TITLE
XCode 8.3.3 compile issue

### ISSUE THREAD

**Issue by myshed** [ksvc/KSYLive_iOS#132]
When i used XCode 8.3.3 to build app against the latest KSYGPUResource and libksygpulive, I got following errors.
![bfb81da17899711e59ea3265221dadd9](https://user-images.githubusercontent.com/4742646/35416353-b96a7ef2-028d-11e8-8d4c-94ad126587a2.png)

If I changed to use XCode 9.2, it was all passed. I just wondering, for XCode 8.3.3 what version of libksygpulive should be used?

Cheers

**Comment by pengbins** [comment]
Please refer to the end of [release note v2.8.0](https://github.com/ksvc/KSYLive_iOS/releases/tag/v2.8.0)

Version prior v2.8.0(not include) should be used for Xcode 8.

**Comment by pengbins** [comment]
Please refer to the end of [release note v2.8.0](https://github.com/ksvc/KSYLive_iOS/releases/tag/v2.8.0)

Version prior v2.8.0(not include) should be used for Xcode 8.
