### ISSUE TITLE
使用推流贴纸功能出现问题

### ISSUE THREAD

**Issue by Czing** [ksvc/KSYLive_iOS#135]
我的项目中直播使用了美颜和滤镜，想使用贴纸功能按照wiki方式_kit.aePic = [[GPUImageUIElement alloc] initWithView:_decalBGView]; 这行代码进行贴纸图层添加，拉流端就出现KSYGPUResource文件下的得一张默认图片黑白的那种 ，得不到自己的做的贴纸，能帮解决下吗

**Comment by jiangdsuccess** [comment]
已解决

**Comment by cheng666666** [comment]
亲，请问下你是怎么解决的呢，我也出现相同的问题了

**Comment by cheng666666** [comment]
> 已解决



> 我的项目中直播使用了美颜和滤镜，想使用贴纸功能按照wiki方式_kit.aePic = [[GPUImageUIElement alloc] initWithView:_decalBGView]; 这行代码进行贴纸图层添加，拉流端就出现KSYGPUResource文件下的得一张默认图片黑白的那种 ，得不到自己的做的贴纸，能帮解决下吗
亲，请问下你是怎么解决的呢，我也出现相同的问题了

**Comment by cheng666666** [comment]
> 我的项目中直播使用了美颜和滤镜，想使用贴纸功能按照wiki方式_kit.aePic = [[GPUImageUIElement alloc] initWithView:_decalBGView]; 这行代码进行贴纸图层添加，拉流端就出现KSYGPUResource文件下的得一张默认图片黑白的那种 ，得不到自己的做的贴纸，能帮解决下吗

亲，请问下你是怎么解决的呢，我也出现相同的问题了
