### ISSUE TITLE
用文档里的动态库生成Framework文件失败

### ISSUE THREAD

**Issue by mengxianliang** [ksvc/KSYLive_iOS#137]
https://github.com/ksvc/KSYLive_iOS/wiki/dylib
用这个教程，下载完成后运行脚本文件，不能打包成功。
建议能否提供一套完善的Framework和依赖库说明，减少集成时间成本。

**Comment by fpzeng** [comment]
你是要集成动态库？
遇到了什么问题？

**Comment by pengbins** [comment]
release 的附件里有动态库下载的, 比如:
https://github.com/ksvc/KSYLive_iOS/releases/download/v3.0.2/framework_dy_v3.0.2.zip

**Comment by mengxianliang** [comment]
我是在Demo里没有找到Framework文件，在教程里看到了生成动态库的教程，就试了一下，但是报错了，没有成功。谢谢 @pengbins ，就是想找这个下载地址。

**Comment by HanYaZhou1990** [comment]
6个月前删除了UIWebView，怎么没有release 3.0.5 的framework啊
