### ISSUE TITLE
能否把ios推流与播流分开？

### ISSUE THREAD

**Issue by advance1989** [ksvc/KSYLive_iOS#14]
我们项目中有用到ijkplayer 与你们sdk中的播放器冲突。  能否把推流与播流分开。或者把你们的播流音频加上nellymoser格式的解码。  需要沟通可以qq 343188225

**Comment by pengbins** [comment]
nellymoser 解码添加中...

**Comment by zhouzizi** [comment]
能否把推流与播流分开。

**Comment by pengbins** [comment]
不能分开的
