### ISSUE TITLE
设置帧率不起作用

### ISSUE THREAD

**Issue by mengxianliang** [ksvc/KSYLive_iOS#143]
我在推流前手动设置了帧率
![](https://raw.githubusercontent.com/mengxianliang/ImageRepository/master/Test/1.png)

推流成功后，用VLC查看流信息中显示，帧率一直是1000
![](https://raw.githubusercontent.com/mengxianliang/ImageRepository/master/Test/2.png)

请问怎样设置帧率才能起作用，我还需要设置一些其他东西才能生效么。

**Comment by mayudong1** [comment]
vlc对某些流可能解析不到帧率或者说显示的这个帧率是错误的，你可以试试其他的工具查看一下帧率

**Comment by mengxianliang** [comment]
请问有其他可以查看帧率工具能推荐一下么，十分感谢！
