### ISSUE TITLE
Use libc++ instead of libstdc++

### ISSUE THREAD

**Issue by jzzocc** [ksvc/KSYLive_iOS#146]
Hello,

This project uses libstdc++, which is removed in iOS 12. Projects using `libksygpulive` will not compile in Xcode 10 ☹️:

<img width="563" alt="screenshot 2018-06-12 14 33 04" src="https://user-images.githubusercontent.com/2831158/41309832-c29207f8-6e4d-11e8-9d40-569ac8398fe6.png">

An Apple engineer says to use libc++ instead: https://twitter.com/jeremyhu/status/1003882060556062720

Thank you!

**Comment by jzzocc** [comment]
This has been resolved in version 3.0.4, thank you!

**Comment by manajay** [comment]
升级3.0.4 后发现 

Undefined symbols for architecture arm64:
  "_avcodec_decode_audio4", referenced from:
      -[KSYBgmReader decodeAudio] in libksystreamerengine.a(KSYBgmReader.o)
  "_swr_convert", referenced from:
      -[KSYAudioMixer pushSample:nbSample:withFormat:timeinfo:ToTrack:] in libksystreamerengine.a(KSYAudioMixer.o)
      -[KSYBgmReader decodeAudio] in libksystreamerengine.a(KSYBgmReader.o)
  "_swr_init", referenced from:
      -[KSYAudioMixer initResample:] in libksystreamerengine.a(KSYAudioMixer.o)
      -[KSYBgmReader initResample:To:] in libksystreamerengine.a(KSYBgmReader.o)
  "_av_buffersrc_add_frame", referenced from:
      -[KSYAudioFilter processAudioData:nbSample:withFormat:timeinfo:] in libksystreamerengine.a(KSYAudioFilter.o)
  "_avfilter_graph_alloc", referenced from:
      -[KSYAudioFilter reconfigure_filter] in libksystreamerengine.a(KSYAudioFilter.o)
  "_avfilter_get_by_name", referenced from:
      -[KSYAudioFilter reconfigure_filter] in libksystreamerengine.a(KSYAudioFilter.o)
  "_av_strlcatf", referenced from:
      -[KSYAudioFilter reconfigure_filter] in libksystreamerengine.a(KSYAudioFilter.o)
  "_avfilter_inout_alloc", referenced from:
      -[KSYAudioFilter reconfigure_filter] in libksystreamerengine.a(KSYAudioFilter.o)
  "_avfilter_graph_free", referenced from:
      -[KSYAudioFilter dealloc] in libksystreamerengine.a(KSYAudioFilter.o)
      -[KSYAudioFilter reconfigure_filter] in libksystreamerengine.a(KSYAudioFilter.o)
  "_avfilter_register_all", referenced from:
      -[KSYAudioFilter init] i
