### ISSUE TITLE
iOS 推流SDK 无法推流

### ISSUE THREAD

**Issue by zhouzizi** [ksvc/KSYLive_iOS#15]
推流报错
codec设置的是X264
kit.streamerBase.videoCodec = KSYVideoCodec.X264

点击推流报如下错误
Could not find AAC encoder
Selected Codec not supported in this version

**Comment by pengbins** [comment]
可能是跟你们其他的ffmpeg库冲突了,  加上 -all_laod 看看吧

**Comment by zhouzizi** [comment]
加了编译就报错，确定项目只有一个ffmpeg库
