### ISSUE TITLE
手动编译framework生成依赖项报错

### ISSUE THREAD

**Issue by xiongjie1207** [ksvc/KSYLive_iOS#151]
======================
== build framework ===
======================
cp: /Users/xiongjie/Documents/KSYLive_iOS-master/releaseFramework/../prebuilt/include//libksygpulive/KSYMediaInfoProber.h and /Users/xiongjie/Documents/KSYLive_iOS-master/releaseFramework/../prebuilt/include//libksygpulive/KSYMediaInfoProber.h are identical (not copied).
cp: /Users/xiongjie/Documents/KSYLive_iOS-master/releaseFramework/../prebuilt/include//libksygpulive/KSYNetTracker.h and /Users/xiongjie/Documents/KSYLive_iOS-master/releaseFramework/../prebuilt/include//libksygpulive/KSYNetTracker.h are identical (not copied).
cp: /Users/xiongjie/Documents/KSYLive_iOS-master/releaseFramework/../prebuilt/include//libksygpulive/KSYMoviePlayerController.h and /Users/xiongjie/Documents/KSYLive_iOS-master/releaseFramework/../prebuilt/include//libksygpulive/KSYMoviePlayerController.h are identical (not copied).
cp: /Users/xiongjie/Documents/KSYLive_iOS-master/releaseFramework/../prebuilt/include//libksygpulive/KSYMediaPlayback.h and /Users/xiongjie/Documents/KSYLive_iOS-master/releaseFramework/../prebuilt/include//libksygpulive/KSYMediaPlayback.h are identical (not copied).
cp: /Users/xiongjie/Documents/KSYLive_iOS-master/releaseFramework/../prebuilt/include//libksygpulive/KSYQosInfo.h and /Users/xiongjie/Documents/KSYLive_iOS-master/releaseFramework/../prebuilt/include//libksygpulive/KSYQosInfo.h are identical (not copied).
cp: /Users/xiongjie/Documents/KSYLive_iOS-master/releaseFramework/../prebuilt/include//libksygpulive/KSYMediaInfo.h and /Users/xiongjie/Documents/KSYLive_iOS-master/releaseFramework/../prebuilt/include//libksygpulive/KSYMediaInfo.h are identical (not copied).
cp: /Users/xiongjie/Documents/KSYLive_iOS-master/releaseFramework/../prebuilt/include//libksygpulive/KSYReachability.h and /Users/xiongjie/Documents/KSYLive_iOS-master/releaseFramework/../prebuilt/include//libksygpulive/KSYReachability.h are identical (not copied).
cp: /Users/xiongjie/Documents/KSYLive_iOS-master/releaseFramework/../prebuilt/include//libksygpulive/KSYMoviePlayerDefines.h and /Users/xiongjie/Documents/KSYLive_iOS-master/releaseFramework/../prebuilt/include//libksygpulive/KSYMoviePlayerDefines.h are identical (not copied).
=====  building libKSYLive - libksygpulive - iphoneos @ Tue Jul 31 15:12:24 CST 2018 
xcrun: error: unable to find utility "xcodebuild", not a developer tool or in PATH
=====  building libKSYLive - libksygpulive - iphonesimulator @ Tue Jul 31 15:12:24 CST 2018 
xcrun: error: unable to find utility "xcodebuild", not a developer tool or in PATH
=====  strip & universal - libksygpulive @ Tue Jul 31 15:12:24 CST 2018 
cp: build/Release-iphoneos/libksygpulive.framework: No such file or directory
build/Release-iphoneos/libksygpulive.framework/libksygpulive: cannot open `build/Release-iphoneos/libksygpulive.framework/libksygpulive' (No such file or directory)
build/Release-iphonesimulator/libksygpulive.framework/libksygpulive: cannot open `build/Release-iphonesimulator/libksygpulive.framework/libksygpulive' (No such file or directory)
fatal error: /Library/Developer/CommandLineTools/usr/bin/lipo: can't open input file: build/Release-iphoneos/libksygpulive.framework/libksygpulive (No such file or directory)
fatal error: /Library/Developer/CommandLineTools/usr/bin/lipo: can't open input file: ../../framework/static/libksygpulive.framework/libksygpulive (No such file or directory)
../../framework/static/libksygpulive.framework/libksygpulive: cannot open `../../framework/static/libksygpulive.framework/libksygpulive' (No such file or directory)
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory

**Comment by xiongjie1207** [comment]
已解决

**Comment by YangKunGit** [comment]
> 已解决

请问如何解决的,  我看了下项目内就没有build这个目录呀

**Comment by MING10** [comment]
怎么解决的呢?
