### ISSUE TITLE
推流奔溃

### ISSUE THREAD

**Issue by zhouzizi** [ksvc/KSYLive_iOS#17]
推流成功，Connecting后Connected， 但是奔溃
![image](https://cloud.githubusercontent.com/assets/9103749/16047843/472de444-3284-11e6-9d33-56fc3a188771.png)

**Comment by pengbins** [comment]
我们GPUImage用的是0.1.7release版的, 会不会GPUImage的版本也不一致呢?

**Comment by zhouzizi** [comment]
我要重新下载SDK试试？

**Comment by zhouzizi** [comment]
我是直接
KSYGPUStreamerKit * kit = [[KSYGPUStreamerKit alloc] initWithDefaultCfg];
[kit startPreview:self.view];
NSString *rtmpSrv  = @"rtmp://test.uplive.ksyun.com/live/888";
NSURL* _hostURL = [[NSURL alloc] initWithString:rtmpSrv];
[kit.streamerBase startStream:_hostURL];
没写其他代码。
