### ISSUE TITLE
iOS 13 刘海屏调用开始推流方法闪退

### ISSUE THREAD

**Issue by mengxianliang** [ksvc/KSYLive_iOS#171]
![](https://github.com/mengxianliang/ImageRepository/raw/master/Test/4.png)

**Comment by Turnarounds** [comment]
你好,请问你解决了吗? 我也遇到相同的问题了

**Comment by mengxianliang** [comment]
后来发现是自己的问题，和金山代码没关系。

**Comment by Turnarounds** [comment]
能加个qq请教一下吗？





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: XianLiang Meng <notifications@github.com&gt;
发送时间: 2019年12月21日 18:54
收件人: ksvc/KSYLive_iOS <KSYLive_iOS@noreply.github.com&gt;
抄送: Turnarounds <512172578@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[ksvc/KSYLive_iOS] iOS 13 刘海屏调用开始推流方法闪退 (#171)




后来发现是自己的问题，和金山代码没关系。
