### ISSUE TITLE
使用私有api<UIWebView>导致项目被拒绝 

### ISSUE THREAD

**Issue by andy80038** [ksvc/KSYLive_iOS#175]
rep -r UIWebView ./                            
Binary file .//Pods/libksygpulive/prebuilt/libs/libksybase.a matches
蘋果現在已經不能用 UIWebView

**Comment by andy80038** [comment]
> rep -r UIWebView ./
> Binary file .//Pods/libksygpulive/prebuilt/libs/libksybase.a matches
> 蘋果現在已經不能用 UIWebView

**Comment by binbins** [comment]
请问你是怎么解决的

**Comment by HanYaZhou1990** [comment]
怎么解决的，我现在也卡这了
