### ISSUE TITLE
能不能将直播的pod放到官方上去

### ISSUE THREAD

**Issue by NathanLi** [ksvc/KSYLive_iOS#20]
pod 'KSYGPULive_iOS', :git => 'https://github.com/ksvc/KSYLive_iOS.git'
这种方式指定下载的方式无法做到相同版本不更新，只要一 update pod 就得下载一次，
而你们的包有 90 M+。这在墙内下一次得几小时，体谅一下吧

**Comment by pengbins** [comment]
可以指定tag的哈, 比如按照下面的方式,应该不会每次都更新了吧

pod 'KSYGPULive_iOS', :git => 'https://github.com/ksvc/KSYLive_iOS.git', :tag => 'v1.5.1.1'

**Comment by NathanLi** [comment]
指定 tag 能在一定程度上解决这个问题， 就是得手动跟踪版本了
