### ISSUE TITLE
NSUInteger  和  KSYMicType_unknow = -1,冲突。麻烦改一下，

### ISSUE THREAD

**Issue by limbo0312** [ksvc/KSYLive_iOS#25]
typedef NS_ENUM(NSUInteger, KSYMicType) {
    /// Built-in microphone on an iOS device
    KSYMicType_builtinMic = 0,
    /// Microphone on a wired headset
    KSYMicType_headsetMic,
    /// 蓝牙设备
    KSYMicType_bluetoothMic,
    
    /// 未知设备
    KSYMicType_unknow = -1,
};

===============
NSUInteger  和  KSYMicType_unknow = -1,冲突。麻烦改一下，

**Comment by fpzeng** [comment]
v1.6.0会修复，8月3日完善上线。

**Comment by fpzeng** [comment]
https://github.com/ksvc/KSYLive_iOS/releases/tag/v1.6.0
已经修复
