### ISSUE TITLE
多流播放，回调通知异常，是个必现bug

### ISSUE THREAD

**Issue by limbo0312** [ksvc/KSYLive_iOS#26]
case：
比如同时播放A、B两路流，当我手动断掉A流的服务器，理论上只应该只有A流的callback『MPMoviePlayerPlaybackDidFinishNotification』的通知回来，但是现在正常播放的B流也回来这个callback通知，是个bug。麻烦处理一下。
# 

另外KSYLive应该是根据bilipili的 ijkPlayer进行修改的吧。可否提供一些修改思路blog，一起进行学习借鉴。
比如七牛云直播，进行了跳帧策略和低延迟策略的两个方向的优化，金山云直播呢，分享一下^_^

**Comment by fpzeng** [comment]
我们优化了秒开，可以实现直播流的快速打开并播放。同时支持直播延时控制。内置的H.265解码器性能也优于openhevc解码20%以上。

**Comment by limbo0312** [comment]
note:多流播放，回调通知异常，是个必现bug

我刚才测试了一下ijkPlayer的通知，多流播放回调的通知是正常的。我猜应该是KSY可能对通知做了一些处理，造成多流播放下回调的错乱，这个应该蛮容易排查的，麻烦看看哦。 @fpzeng

**Comment by shixuemei** [comment]
这个问题我们在v1.6.2的版本中已经修复掉了
