### ISSUE TITLE
播放端有时候没有声音

### ISSUE THREAD

**Issue by NathanLi** [ksvc/KSYLive_iOS#27]
推流是由安卓推的，有时候有声音，有时候没有。
但视频都是有的。
而安卓则没有这问题。
版本是v1.5.4

**Comment by fpzeng** [comment]
请夜读：https://github.com/ksvc/KSYMediaPlayer_iOS/wiki/reload
请确认MPMoviePlayerSuggestReloadNotification正确响应了
