### ISSUE TITLE
pod仓库建议放到pod git仓库上，避免每次都需要花费长时间下载KSYLive.git进行pod集成

### ISSUE THREAD

**Issue by limbo0312** [ksvc/KSYLive_iOS#28]
现在KSYLive是使用这种方式进行pod集成，
pod 'KSYGPULive_iOS', :git => 'https://github.com/ksvc/KSYLive_iOS.git'

这样有个坏处，
1、没有是用上pod local cache仓库。当相同版本的时候不需要每次都进行下载；
2、版本识别不明显。

强烈建议使用pod 官方的仓库。

==================
liangmingwei$ pod search KSYlive
[!] Unable to find a pod with name matching `KSYlive'

**Comment by NathanLi** [comment]
你可以指定tag 
  pod 'KSYGPULive_iOS', :git => 'https://github.com/ksvc/KSYLive_iOS.git', :tag => 'v1.6.0'

**Comment by fpzeng** [comment]
如果是国内访问，可以通过oschina下载。具体地址请见：<https://github.com/ksvc/KSYLive_iOS/blob/master/README.md>
同时我们也在pod官方库中有对应版本，请使用如下spec库：
```
pod search KSYGPULive_iOS
```

**Comment by NathanLi** [comment]
不容易，终于加到官方库中了

**Comment by limbo0312** [comment]
酷。官方的还是非常必须的。单从pod local cache考虑，再加上tag这个用法确实不是最熟悉的用法。
辛苦了
pod search KSYGPULive_iOS

**Comment by pengbins** [comment]
~ xxx$ pod search libksygpulive
-> libksygpulive (1.8.4)
   libksylive help you play and stream live video from ios mobile devices.
   pod 'libksygpulive', '~> 1.8.4'
   - Homepage: http://v.ksyun.com/doc.html
   - Source:   https://github.com/ksvc/KSYLive_iOS.git
   - Versions: 1.8.4, 1.8.3, 1.8.2, 1.8.1, 1.8.0 [master repo]
   - Subspecs:
     - libksygpulive/KSYMediaPlayer (1.8.4)
     - libksygpulive/KSYMediaPlayer_vod (1.8.4)
     - libksygpulive/libksygpulive (1.8.4)
     - libksygpulive/libksygpulive_265 (1.8.4)
     - libksygpulive/KSYGPUResource (1.8.4)
