### ISSUE TITLE
新的sdk新增文件？

### ISSUE THREAD

**Issue by zhouzizi** [ksvc/KSYLive_iOS#29]
新的sdk新增了一个framework是干嘛用的。是否需要导入
![image](https://cloud.githubusercontent.com/assets/9103749/17460387/d4870f78-5c96-11e6-90f7-dc6e3aa74524.png)
导入后
![image](https://cloud.githubusercontent.com/assets/9103749/17460388/e10e9c3e-5c96-11e6-8ea7-41bb6ac60c11.png)

**Comment by fpzeng** [comment]
我们支持了动态库，具体wiki说明请见 
<https://github.com/ksvc/KSYLive_iOS/wiki/dylib>

**Comment by zhouzizi** [comment]
耳返是否支持混响？

**Comment by pengbins** [comment]
可以看下KSYAUAudioCapture 这个类, 同时支持 混响 和耳返 的 采集模块 

http://ksvc.github.io/KSYLive_iOS/doc/html/Classes/KSYAUAudioCapture.html
