### ISSUE TITLE
引用三个framework在ios7上编译报错

### ISSUE THREAD

**Issue by zichengbohan** [ksvc/KSYLive_iOS#30]
#import <GPUImage/GPUImage.h>
#import <libksygpulive/libksygpulive.h>
#import <libksygpulive/libksygpuimage.h>
无法在ios7上编译
ld: embedded dylibs/frameworks are only supported on iOS 8.0 and later (@rpath/libksygpulivedylib.framework/libksygpulivedylib) for architecture arm64

**Comment by fpzeng** [comment]
我们新增了动态库，如果需要支持iOS 7.0，请见动态库说明：
<https://github.com/ksvc/KSYLive_iOS/wiki/dylib>
静态库、动态库二者选其一，无需都引用

**Comment by zichengbohan** [comment]
好的 谢谢 辛苦
