### ISSUE TITLE
美颜 新美白KSYGPUBeautifyProWhitenFilter 的类找不到，请问怎么使用这个效果

### ISSUE THREAD

**Issue by zichengbohan** [ksvc/KSYLive_iOS#31]
新美白KSYGPUBeautifyProWhitenFilter 的类找不到，请问怎么使用这个效果

**Comment by fpzeng** [comment]
还在内测中，会择机发布，请关注我们的release note。
<https://github.com/ksvc/KSYLive_iOS/releases>

**Comment by leewaycn** [comment]
KSYGPUBeautifyProFilter	新美颜	21.85%	21%	20.4%	22.7%	30	33.1
KSYGPUBeautifyProSharpenFilter	新锐化	21.85%	25.2%	20.4%	31.6%	30	33.1
KSYGPUBeautifyProWhitenFilter 找不到。

**Comment by pengbins** [comment]
新的美颜类 已经放出了 名字 改为 [KSYBeautifyFaceFilter](http://ksvc.github.io/KSYLive_iOS/doc/html/Classes/KSYBeautifyFaceFilter.html)
