### ISSUE TITLE
多次进出直播间时，严重掉帧

### ISSUE THREAD

**Issue by NathanLi** [ksvc/KSYLive_iOS#33]
如题，在观众端，短时间内，多次进出直播间时，出现严重掉帧的问题。

**Comment by fpzeng** [comment]
请问推流的配置：gop/分辨率/码率/fps
掉帧的具体表现是卡顿还是刷新帧率低？

**Comment by NathanLi** [comment]
推流：gop:1  分辨率是自动的（设置是 iPhone6s） 码率是200KB fps: 20
具体表现是：刷新帧率低  感觉像是 1s 刷2次，但下载的速度是正常的  120KB左右
