### ISSUE TITLE
官方库不行哦。报错如下

### ISSUE THREAD

**Issue by leewaycn** [ksvc/KSYLive_iOS#34]
Resolving dependencies of `Podfile`
[!] Unable to find a specification for `KSYGPULive_iOS`

**Comment by leewaycn** [comment]
pod search KSYGPULive_iOS
Creating search index for spec repo 'master'.. Done!
[!] Unable to find a pod with name, author, summary, or descriptionmatching `KSYGPULive_iOS`
为什么呢？

**Comment by pengbins** [comment]
建议使用  新版本的 [libksygpulive](https://cocoapods.org/pods/libksygpulive)
pod search libksygpulive
