### ISSUE TITLE
横屏推流，要设置哪些因素呢？

### ISSUE THREAD

**Issue by leewaycn** [ksvc/KSYLive_iOS#37]
布局已经横过来了。可是推流还是竖的。

**Comment by sunjian880928** [comment]
嗨，在竖屏切换到横屏要先停止预览和推流，然后在重新开始预览和推流

**Comment by pengbins** [comment]
请问横屏推流设置成功了么?

在demo和kit类里面, 其实只要启动预览时, UI的朝向(状态栏)为横屏, 那么推流就会是横屏, 

最关键的接口是kit类中的vCapDev. outputImageOrientation 这个属性, 设置为横屏, 那么采集输出的图像就是宽度大于高度的. kit类中,是每次启动采集前, 读取UI朝向, 对其进行赋值.

主要是如果脱离UI朝向, 预览朝向, 这个东西单独设置起来会很困惑, 建议保持UI朝向,预览朝向, 推流朝向三者一致.
