### ISSUE TITLE
在推流时，多次手动锁屏再启动的BUG

### ISSUE THREAD

**Issue by NathanLi** [ksvc/KSYLive_iOS#41]
在推流正常的情况下，手动锁屏再启动应用，尝试继续推流时，会有摄像头打不开的情况，无法再继续推流了。有时，锁屏一次就会，有时需要多次。

**Comment by pengbins** [comment]
可以先将KSYGPUCamera的 bPauseCaptureOnNotice 属性设为 NO 试试看

**Comment by NathanLi** [comment]
没有用
