### ISSUE TITLE
1.8.0 的推流里，KSYVideoDimension 没有用了？

### ISSUE THREAD

**Issue by NathanLi** [ksvc/KSYLive_iOS#43]
而且好像 micMonitor 也没了。

**Comment by pengbins** [comment]
对,  KSYVideoDimension 没有用到了, 分辨率的设置方法修改了一下
可以 参考如下 wiki 页面 https://github.com/ksvc/KSYLive_iOS/wiki/captureParams#%E5%88%86%E8%BE%A8%E7%8E%87

主要是推流过程中存在如下3个分辨率: 
* 采集分辨率 : 直接使用Apple定义的preset来设置
* 预览分辨率 和推流分辨率  可以直接通过  CGSize 来指定, 通过GPU后, 可以很方便做到缩放, 减少了CPU上做缩放的消耗

**Comment by pengbins** [comment]
micMonitor 这个类的功能合并到了新的音频采集模块中KSYAUAudioCapture

通过设置bPlayCapturedAudio 属性可以实现完全相同的功能
