### ISSUE TITLE
1.8.4 在Xcode8.1下编译不通过

### ISSUE THREAD

**Issue by pzee** [ksvc/KSYLive_iOS#52]
系统:os x 10.2.1
软件：Xcode8.1
通过cocoapods 安装libksygpulive，执行pod install 后，运行项目编译不通过。
提示 
xxx/Pods/Headers/Public/libksygpulive/KSYGPUStreamerKit.h:73:48: Unknown class name 'GPUImageInput'; did you mean 'GPUImageOutput'?
xxx/Pods/Headers/Public/libksygpulive/KSYGPUStreamerKit.h:73:48: Type argument 'GPUImageOutput' must be a pointer (requires a '*')
...
需要如何处理呢

**Comment by pengbins** [comment]
估计是 头文件的问题吧, 在import KSYGPUStreamerKit.h之前, 得先import 一下 GPUImage的头文件

```
#import <GPUImage/GPUImage.h>
#import "KSYGPUStreamerKit.h"
```

**Comment by pzee** [comment]
是的，我直接修改头文件了
分别引入
#import "KSYTypeDef.h"
#import <GPUImage/GPUImage.h>

@class KSYGPUPicMixer;
@class KSYAVAudioSession;
@class KSYStreamerBase;
