### ISSUE TITLE
我按照手动编译方法打包后，发现GPUImage.framework 下面有很多重复的GPUIMAGE。

### ISSUE THREAD

**Issue by leewaycn** [ksvc/KSYLive_iOS#53]
3.3.2 手动编译framework生成依赖项运行示例demo

将SDK 打包为framework
将压缩包解压(或者clone成功)后, 进入 releaseFramework 目录, 通过 release-libKSYLive.sh 下载依赖项并打包出framework，生成到KSYLive_iOS/framework目录下。

$ cd releaseFramework
$ ./release-libKSYLive.sh libksygpulive lite
$ ls ../framework
Bugly.framework  GPUImage.framework  libksygpulive.framework

我按照这个方法打包后，发现GPUImage.framework 下面有很多重复的GPUIMAGE。

**Comment by pengbins** [comment]
重复的文件已经去掉了, 请删掉framework目录后重新执行脚本试试看吧
