### ISSUE TITLE
mp4录制失败

### ISSUE THREAD

**Issue by cbangchen** [ksvc/KSYLive_iOS#57]
![image](https://cloud.githubusercontent.com/assets/11977680/20469780/73f12adc-afdd-11e6-8d0b-cd328ab9e35b.png)

![image](https://cloud.githubusercontent.com/assets/11977680/20469467/ebe9b3e0-afda-11e6-928d-6626a33a9059.png)

![image](https://cloud.githubusercontent.com/assets/11977680/20469775/64f8a4a6-afdd-11e6-89a7-292e875d9dad.png)

![image](https://cloud.githubusercontent.com/assets/11977680/20469785/7f70b94a-afdd-11e6-877c-950256e0b915.png)

**Comment by pengbins** [comment]
KSYStreamerbase内部是包含了编码器的, 接收的sample buffer 需要原始的yuv数据, 目前不支持编码后的数据

**Comment by cbangchen** [comment]
不是很明白，如果是这样的话，为什么又会有一个接口是
```
/**
 @abstract  处理一个视频帧
 @param pixelBuffer 待编码的像素数据
 @param timeStamp   待编码的时间戳
 @discussion 应当在开始推流前定期调用此接口，比如按照采集帧率调用
 */
- (void)processVideoPixelBuffer:(CVPixelBufferRef)pixelBuffer
                       timeInfo:(CMTime)timeStamp;
```
这才是未编码数据的传输接口吧

**Comment by pengbins** [comment]
这两个接口都是未编码数据的传输接口, 只是数据类型不同

**Comment by cbangchen** [comment]
服气

**Comment by pengbins** [comment]
现在的接口里  CMSampleBufferRef = CVPixelBufferRef + CMTime
内容没有区别的

**Comment by cbangchen** [comment]
音视频都是未编码的吗

**Comment by pengbins** [comment]
对的, 音频是pcm的, 只支持  S16, 单声道

如果有其他格式的PCM, 建议先送到 mixer, mixer有PCM格式转换的功能

**Comment by cbangchen** [comment]
可以，推流和信息采集耦合的那么强。

**Comment by pengbins** [comment]
采集和推流已经没有太多耦合了, 通过图像和音频的mixer, 可以很灵活组合吧

**Comment by cbangchen** [comment]
说的也是

**Comment by cbangchen** [comment]
![image](https://cloud.githubusercontent.com/assets/11977680/20659057/2e5364be-b57c-11e6-9bd8-c1416be1a82f.png)

![image](https://cloud.githubusercontent.com/assets/11977680/20659068/3b6fd8da-b57c-11e6-9e0d-01dc095dd6c6.png)

KSYRecordErrorInternal

**Comment by cbangchen** [comment]
@pengbins

**Comment by pengbins** [comment]
还有别的线索么? 看起来一切正常呀

**Comment by cbangchen** [comment]
出现了一个 log : Error occurred when opening output file ，是sdk里面输出的吗

**Comment by cbangchen** [comment]
![image](https://cloud.githubusercontent.com/assets/11977680/20659898/7dfe182e-b581-11e6-9d12-ce4b3df7e21c.png)

**Comment by pengbins** [comment]
嗯, 是SDK 输出的错误日志

**Comment by pengbins** [comment]
启动录制太早了, 建议等推流启动成功之后, 在启动旁路录制

**Comment by cbangchen** [comment]
推流地址是错的，我随便填的。

**Comment by pengbins** [comment]
比如 收到状态变化通知, 当前状态为 KSYStreamStateConnected 之后再启动录制

毕竟是旁路录制, 如果没有成功推流, 录制也不好开始

**Comment by pengbins** [comment]
有关系的哈, 旁路录制,必须要推流成功后才行

**Comment by pengbins** [comment]
如果不需要推流, 建议直接使用录制接口, 就是直接把rtmp地址换成本地地址.

**Comment by pengbins** [comment]
![image](https://cloud.githubusercontent.com/assets/1439218/20660067/6aaf6a56-b582-11e6-824e-5bc04632263a.png)

**Comment by cbangchen** [comment]
可以了，给你点100个赞。收下。

**Comment by cbangchen** [comment]
我。。。你们sdk不支持后台视频推流啊，一进入后台就断掉了，我的信号还是不断传输的。

**Comment by pengbins** [comment]
额, 理论上是支持的呀, 音频能在后台采集, 也能推流呀

**Comment by cbangchen** [comment]
对于VTDecompressionSessionDecodeFrame的后台运行，是怎么处理的

**Comment by cbangchen** [comment]
我这边是要实现后台视频推流的部分，看了一下，进入后台编码回调就不执行了，返回status错误也千奇百怪，请问sdk里面除了返回前台时候重新初始化session外还有什么处理方式吗？能够实现后台编码。

**Comment by pengbins** [comment]
所以你们把  bWithAudio = NO了?

**Comment by pengbins** [comment]
没有后台执行权限的话, 整个app在后台都会被挂起的
目前我们SDK只能保证, 在音频采集仍然工作的情况下, 音视频编码能正常工作

**Comment by cbangchen** [comment]
后台的权限设置了的，audio和AirPlay那个，bWithAudio确实设置为NO了，音频编码和视频的videotool编码还是不同，你所说的音视频编码可以正常工作，我可以理解为，只要开启音频推流，视频后台编码也可以实现？

**Comment by pengbins** [comment]
对, 只要能保证在后台期间音频推流是正常的,  那么同时持续送入图像的话, 视频编码就是正常的

**Comment by pengbins** [comment]
对了, 那你们在后台的时候, 图像的来源是啥?

**Comment by cbangchen** [comment]
屏幕录制

**Comment by cbangchen** [comment]
我这边自己尝试进行编解码时，进入后台的回调是不执行的，想知道你们对于这一部分内容是怎么处理的？

**Comment by pengbins** [comment]
额, 必须得编码了, 才能推流呀

**Comment by pengbins** [comment]
可以在1.9.2 上试一下看, 应该在后台也会编码图像(重复的同一帧)并发送出去

**Comment by cbangchen** [comment]
嗯嗯，我后面发现是解码的时候才有session失效的问题，是苹果那边的bug

**Comment by cbangchen** [comment]
谢谢你的解答。
