### ISSUE TITLE
releaseFramework

### ISSUE THREAD

**Issue by qiujinWang** [ksvc/KSYLive_iOS#58]
releaseFramework里面的库文件都丢失了！请检查！

**Comment by pengbins** [comment]
![image](https://cloud.githubusercontent.com/assets/1439218/20584765/d268e0f0-b230-11e6-9583-d5a4c86f6004.png)

是这个问题么?

Products 里面是编译生成的内容哈, 红色表明没有生成而已, 并不是丢失了

另外请**不要**直接使用releaseFramework/libKSYLive/libKSYLive.xcodeproj 这个工程 

请执行releaseFramework/release-libKSYLive.sh 来得到你需要的framework, 详情参考脚本帮助

脚本输出的内容请到framework/ 下去找

**Comment by pengbins** [comment]
库文件可以到 github 的 release 附件中下载了, 一般不用去执行这个脚本了
