### ISSUE TITLE
Swift下 ios10崩溃

### ISSUE THREAD

**Issue by liyun2060** [ksvc/KSYLive_iOS#59]
在真机下 ios8没问题，但是IOS10 推流就会崩溃

**Comment by pengbins** [comment]
实测 在iPhone6s,  iOS10.0.1 , 推流没有crash的

请检查一下开始推流端的地址是否合法吧

**Comment by pengbins** [comment]
![image](https://cloud.githubusercontent.com/assets/1439218/21135081/7a7f14d8-c15b-11e6-9154-e9d80e362461.png)

**Comment by pengbins** [comment]
这位同学也跑起来了

https://github.com/manajay/KSYLiveDemo_Swift.git
