### ISSUE TITLE
启动旁路录像 崩溃

### ISSUE THREAD

**Issue by taiheile** [ksvc/KSYLive_iOS#61]
保存路径:/var/mobile/Containers/Data/Application/APPID/Documents/Movie.m4v

崩溃 提示:Could not create output context

**Comment by pengbins** [comment]
我们目前不支持m4v, 只支持 mp4和flv

**Comment by taiheile** [comment]
谢谢 已解决  是我疏忽了

**Comment by pengbins** [comment]
😄
