### ISSUE TITLE
swift 3.0 点不出来  appEnterBackground 切换前后台的方法

### ISSUE THREAD

**Issue by manajay** [ksvc/KSYLive_iOS#62]
```
- (void)enterBg:(NSNotification *)not{  //app will resigned
    [_kit appEnterBackground];
}

- (void) becameActive:(NSNotification *)not{ //app becameAction
    [_kit appBecomeActive];
}
```

**Comment by manajay** [comment]
![63a64dc3-bb92-45d5-bf23-4797e84a7382](https://cloud.githubusercontent.com/assets/13750333/21631688/46fb45e4-d279-11e6-8ab6-0167ec34772e.png)
![c5277d57-9139-4493-84e5-1f4ee6beb01e](https://cloud.githubusercontent.com/assets/13750333/21631689/4ce414cc-d279-11e6-9757-04c62c1df916.png)
第一张为swift自动生成的接口API, 第二张为 OC的接口, 少了几个API

**Comment by pengbins** [comment]
![image](https://cloud.githubusercontent.com/assets/1439218/21635642/ccbe2370-d299-11e6-9094-ede347ccfde6.png)

我们这边能看到 appEnterBackground 和 appBecomeActive 的

**Comment by pengbins** [comment]
xcode 的symbol navigator 貌似不是按字母顺序的, 你往下翻一点就看到这两个函数的了

**Comment by manajay** [comment]
@pengbins  是因为官方库的版本问题,cocoapod私有的那个地址 ,版本就是最新的了,使用官方的trunk 是没有这些API的

**Comment by pengbins** [comment]
哦, 那可能需要 先 执行 $ pod repo update  , 把 cocoapod的trunk更新一下
pod install 之后 看下  libksygpulive的版本吧, 在1.9.4上肯定是没问题的
