### ISSUE TITLE
横屏的时候初始化,预览画面加载失败

### ISSUE THREAD

**Issue by manajay** [ksvc/KSYLive_iOS#63]
![img_3098](https://cloud.githubusercontent.com/assets/13750333/21631656/c58a0b44-d278-11e6-9845-a59d15fd9ec5.PNG)
![img_3099](https://cloud.githubusercontent.com/assets/13750333/21631657/c5d5e6ae-d278-11e6-9d4e-5fba4b87b4c6.PNG)
上面的两张图,一张是 初始化 黑屏,没有加载预览图像,点击美颜后就正确显示, 另一张是 只显示的部分,也就是说 预览没有跟随UI横屏
两种情况 黑屏的出现几率高一点,但也是差不多
使用xcode8.2.1 swift3.0

**Comment by pengbins** [comment]
应该是视图布局相关的问题

**Comment by manajay** [comment]
确实是 布局的原因
`
  @objc fileprivate func onCaptureStateChange(_ notification:Notification) {
    if kit.vCapDev.isRunning {
      kit.preview.snp.makeConstraints({ (make) in
        make.edges.equalToSuperview()
      })
    }
    
  }
`
主要是preview的尺寸问题,并不是没有出来,而是 size为 zero的原因
