### ISSUE TITLE
flash端推流，编码格式是speex，移动端不能支持speex，没有声音

### ISSUE THREAD

**Issue by xiongjie1207** [ksvc/KSYLive_iOS#67]
flash端推流，编码格式是speex，移动端不能支持speex，没有声音，怎么处理呢

**Comment by fpzeng** [comment]
我们当前支持NellyMoser的播放，如果需要支持Speex，需要等待一周以后的版本发布。谢谢

**Comment by xiongjie1207** [comment]
嗯嗯，好的，谢谢

**Comment by fpzeng** [comment]
已经上线，请试用：
https://github.com/ksvc/KSYLive_iOS/releases/tag/v2.0.1

**Comment by xiongjie1207** [comment]
好的，多谢

**Comment by xiongjie1207** [comment]
好的，多谢
