### ISSUE TITLE
引入趣拍sdk后，我用金山sdk拉流6s后自动崩溃

### ISSUE THREAD

**Issue by leewaycn** [ksvc/KSYLive_iOS#68]
我这里用的是金山SDK做推拉流。
想接入趣拍的短视频。
但我将趣拍的标准版SDK拉入我的工程后，没曾加入代码。
当我拉流的时候，大概 5､6秒后自动闪退。
无报错信息。[https://www.qupaicloud.com/SYSTEM/e565a290-725f-410c-a33f-72ae70f53dbe](url)

**Comment by leewaycn** [comment]
趣拍反馈的信息：

金山SDK使用了toString方法和我们有冲突，请反馈给金山修改方法名，我们这边也会做相应修改。

**Comment by pengbins** [comment]
> nm -nm static/libksygpulive.framework/libksygpulive | grep toString

我们SDK里貌似没有toString的方法

**Comment by leewaycn** [comment]
升级到V2.0.0后解决。忘记了说我之前用的是V1.9.5了。
