### ISSUE TITLE
C++编译错误

### ISSUE THREAD

**Issue by ElfSundae** [ksvc/KSYLive_iOS#7]
建议将`KSYCamera.h`里的`@import AVFoundation;` 改为`#import <AVFoundation/AVFoundation.h>`. 
项目里如果有C++/ObjC++文件引用`<libksygpulive/libksygpulive.h>`，Xcode就会报错:

```
Pods/KSYGPULive_iOS/framework/livegpu/libksygpulive.framework/Headers/KSYCamera.h:10:1: Use of '@import' when modules are disabled
```
@yulin6666

**Comment by longxiaoming** [comment]
2016-05-04 20:59:50.896 LMLive[1995:600540] *** -[KSYBgmPlayer interruptHandler:]: message sent to deallocated instance 0x1701b8b80 从后台切换到前台时会报这个

**Comment by pengbins** [comment]
已修复
