### ISSUE TITLE
swift项目集成金山云推流SDK后,有时候推流会卡死界面,必须重启手机才行[非常严重]

### ISSUE THREAD

**Issue by manajay** [ksvc/KSYLive_iOS#70]
推流卡死手机的现场,复现率还是不低, 基本iphone6,6s,7都出现过卡死的现象.
>1
https://ooo.0o0.ooo/2017/03/06/58bcda4106c7b.png
https://ooo.0o0.ooo/2017/03/06/58bcda4d939f8.png
2>
https://ooo.0o0.ooo/2017/03/06/58bcda4d9461d.png
3>
https://ooo.0o0.ooo/2017/03/06/58bcda4aea555.png
4>
https://ooo.0o0.ooo/2017/03/06/58bcda4ce1d5b.png
https://ooo.0o0.ooo/2017/03/06/58bcda4de7b67.png

**Comment by alanwang-dev** [comment]
@manajay 关于卡死界面，是卡主线程了还是UI不响应手势了，是需要重启app还是手机卡死了需要重启手机？app能否切后台或锁屏？如果可以的话，是否能提供个可以复现问题的demo？

**Comment by manajay** [comment]
应该是线程问题，只当然推流界面卡死了，操作手机的任何东西都没有效果 唯一能做的就是 强制重启手机。这个应该是网络差点的话会容易复现，我的6p的复现率不是太好。6s的复现率高一点。

2017年3月7日 +0800 PM2:09 Kecheng <notifications@github.com>，写道：

**Comment by manajay** [comment]
https://github.com/manajay/KSYLiveDemo_Swift
这个是我的demo地址，用了一个第三方的计时器。还有一个额外的写入本地沙盒日志的方法。
项目中在直播推流这块主要遇到的就是卡死和横竖屏进入推流或者离开的时候 崩溃（总是报错UIAlertViewController 的没有支持方向bug）的问题。现在 卡死是重中之重。复现的推流时间不确定，同一台手机 有时候可以几分钟 有时候一个多小时也不出来。

2017年3月7日 +0800 PM2:09 Kecheng <notifications@github.com>，写道：

**Comment by alanwang-dev** [comment]
@manajay 已确定问题为外部循环引用导致，不是SDK自身问题，close该 issue
