### ISSUE TITLE
开始预览就已经采集音频了？如果音频被其他第三方占用，RTMP推流不成功也不失败，推流不成功

### ISSUE THREAD

**Issue by adronfan** [ksvc/KSYLive_iOS#79]
1. 这边开启预览，可以看到摄像头采集到的视频流。但是应用退到后台，发现顶部有红条。说明采集视频流的同时也采集了音频（1.1 增加耗电 1.2 不合理，预览怎么采集音频了？）
2. RTMP推流组件仅仅是推流，为什么一定要KSY SDK获取到音频权限才可以？和声网组合使用，声网加入房间会自动获取音频。这时候进行RTMP推流，就一直不成功也不失败，卡在RTMP连接中状态。这很不合理，RTMP的推流需要的音频是可以混音后提供的。你们的Demo也是拿到声网的音频数据然后做混音，说明音频和RTMP推流建立的成功失败根本没有关系。但是目前KSY SDK，拿不到音频权限，就没有办法推流成功（你们在后面的升级Demo里面，在声网离开房间后重启了KSY的aCapDev，重启卡顿时间有0.5-1秒钟啊！！！）

**Comment by pengbins** [comment]
1. 你好, 我们KSYGPUStreamerKit 这个类的代码是开放的哈,主要作用是个示例, 有特别的需求, 每个用户都可以继承它或直接修改.

2. 我们之前理解的预览包括了图像的预览和声音的预览, 主播可以在预览阶段通过耳返来调试音效.   
可以把开始预览理解为开始采集

3. RTMP推流组件 在我们SDK里 指的是 KSYStreamerBase, 这个类没有尝试获取音频权限的

4. "卡在RTMP连接中状态" 应该是没有音频数据送到我们

5. 跟声网组合的情况,请参考我们多样化的[demo](https://github.com/ksvc/KSYDiversityLive_iOS/tree/master/agoraRtc)

**Comment by yulin6666** [comment]
试了一下，去掉重启的逻辑，推流也是会成功的，基于2.0.3版本，你可以试试

**Comment by adronfan** [comment]
好的，谢谢

**Comment by pengbins** [comment]
从v2.1.1 开始, kit增加了 startVideoCap: 和 startAudioCap: 方法, 如果需要分别控制视频和音频采集, 可以考虑这两个方法.

startPreview 仍然保留着, 内部就是先后调用以上两个方法, 启动采集和预览.
