### ISSUE TITLE
Xcode编译警告⚠️

### ISSUE THREAD

**Issue by ElfSundae** [ksvc/KSYLive_iOS#8]
`pod 'KSYGPULive_iOS', :git => 'https://github.com/ksvc/KSYLive_iOS.git'`

Xcode 7.2.1

![qq20160407-0](https://cloud.githubusercontent.com/assets/526008/14349098/372b721c-fcf3-11e5-913c-0283df3acecd.png)

**Comment by fpzeng** [comment]
恩，warning是存在，我们后续会修复，谢谢。

**Comment by pengbins** [comment]
使用cocoapod的方式集成时, 不会有类似的警告了
