### ISSUE TITLE
在拉流的时候，经常报出-10001的错误码

### ISSUE THREAD

**Issue by xiongjie1207** [ksvc/KSYLive_iOS#95]
在拉流的时候，当结束原因为MPMovieFinishReasonPlaybackError时，userInfo字典中的关键字error报出-10001的错误码，听不到对方的声音，请问这个是什么原因？谢谢
-----------------------------------
已解决

**Comment by shixuemei** [comment]
请问您播放视频使用的流媒体协议是什么？-10001错误码表示的是不支持的流媒体协议https://github.com/ksvc/KSYMediaPlayer_iOS/wiki/errorCode，建议您把可用的url发出来我们看一下

**Comment by xiongjie1207** [comment]
已经解决了，谢谢
