### ISSUE TITLE
使用私有api<UIStatusBarDataNetworkItemView>导致项目被拒绝

### ISSUE THREAD

**Issue by 15037535383** [ksvc/KSYLive_iOS#96]
使用私有api<UIStatusBarDataNetworkItemView>导致项目被拒绝

**Comment by 15037535383** [comment]
终端搜索如下:
$ grep -r UIStatusBarDataNetworkItemView .
Binary file ./Pods/libksygpulive/prebuilt/libs/libksybase.a matches
Binary file ./Pods/libksygpulive/prebuilt/libs/libksystreamerbase.a matches

**Comment by 15037535383** [comment]
sdk version = 2.4.0.0

**Comment by fpzeng** [comment]
https://github.com/ksvc/KSYLive_iOS/releases/tag/v2.4.1
已经更新
