### ISSUE TITLE
Preview Camera on 推流demo page not show on swift demo

### ISSUE THREAD

**Issue by kazekim** [ksvc/KSYLive_iOS#97]
I've tried your library and try to use it to live stream video to stream server. But after I entered stream page in swift demo, the preview video was not show. the other one with objc worked well. Do  anyone here found this problem too? Can you tell me how to fix it?

Thanks

**Comment by pengbins** [comment]
We can't re-produce this problem. Can you try the newest version SDK again? or give us some more information.
