### ISSUE TITLE
Can using Third party for audio mixer like The Amazing Audio Engine

### ISSUE THREAD

**Issue by dieunt** [ksvc/KSYLive_iOS#99]
Can i integrate or is there any API or callback function with TAAE or AudioKit for better audio effect? 
Thank.

**Comment by pengbins** [comment]
Yes, of cause. You can use TAAE or AudioKit to replace the audio capture (KSYAUAudioCapture).
TAAE can produce CMSamplebuffer with audio pcm data. Feed these data to KSYAudioMixer (or directly to KSYStreamerBase) should work.

**Comment by pengbins** [comment]
FYI, The Amazing Audio Engine has been [retired](http://theamazingaudioengine.com/retirement/).

**Comment by dieunt** [comment]
You don’t know how happy i’m when get your email.

Thank you very much.

About the emoticon add on live camera, if i want add more emoticon design by myself, what should i do? Should i buy the license? Are you using Faceunity?

Thank you.

**Comment by pengbins** [comment]
For static emoticon, we have demonstrate this function in our demo project, and here is the [doc](https://github.com/ksvc/KSYLive_iOS/wiki/StaticDecalsStream).

And There are some examples of dynamic emoticon 
 based on face landmark in [KSYDiversityLive_iOS](https://github.com/ksvc/KSYDiversityLive_iOS).
Faceunity is included

And you can get support from [ksvcmc](https://github.com/ksvcmc)

**Comment by dieunt** [comment]
I’ll check it out. Many thank for you support. 

Have a nice day.

**Comment by dieunt** [comment]
One more question, please. 

I can’t read Chinese, so could you please let me know, how much does this fantastic library?

Do you have price list for using KSY SDK?

Thank you.

**Comment by fpzeng** [comment]
There is so many suppliers providing dynamic emotion which can be intergrated with KSY Live Streaming SDK, such like [sensetime](sensetime.com) and [faceunity](http://www.faceunity.com/index_eg.html). 
Please contact them, and you can obtain a price list.
